### ISSUE TITLE
new WideQ api is out, can you update the home bridge plugin??

### ISSUE THREAD

**Issue by jmh600cbr** [NorDroN/homebridge-wideq#1]
[According to this thread the API is updated and this home bridge plug is now broken](https://www.reddit.com/r/homebridge/comments/et3sgs/trying_to_get_wideq_for_smartq_washing_machine_to/)

Can you please update this home bridge plugin to work with the [new api](https://github.com/gladhorn/wideq/tree/api2_merged)?

**Comment by NorDroN** [comment]
Hi!
HB + wideq (python) works unstable and often breaks.
In the near future I'll publish a new version of this package that will work with the [wideq (nodejs)](https://github.com/NorDroN/wideq-js) library and without the wideq (python) library.

**Comment by NorDroN** [comment]
Try updating the version of this plugin.

**Comment by jmh600cbr** [comment]
Completely broke my Homebridge setup when running Homebridge I now get this:
"Error: The requested platform 'WideQ' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
“


Help!!?






Joshua Harris
joshharris@gmail.com <mailto:joshharris@gmail.com>

**Comment by jmh600cbr** [comment]
I've tried reinstalling it many many times and even tried putting sudo in front of the code

when putting sudo in front this is the output

joshuas-imac:~ joshuaharris$ sudo npm install -g homebridge-wideq wideq
/usr/local/bin/wideq -> /usr/local/lib/node_modules/wideq/dist/cli.js
+ homebridge-wideq@0.1.2
+ wideq@1.0.0
updated 2 packages in 1.69s

**Comment by NorDroN** [comment]
Does it work correct after installed via sudo or not?

**Comment by jmh600cbr** [comment]
Nope. Same issue.

**Comment by NorDroN** [comment]
Please, share your config file.

**Comment by jmh600cbr** [comment]
> Please, share your config file.

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
    },
    "accessories": [
        {
            "accessory": "HubbleCameraTemp",
            "name": "Baby room temperature",
            "host": "192.168.86.33",
            "update_interval": 60
        }
    ],
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "name": "wendy",
            "hubIP": "192.168.86.22",
            "TVPlatformMode": true,
            "mainActivity": "Watch Apple TV"
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true,
            "log": {
                "method": "file",
                "path": "/var/log/homebridge.log"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "D-Link Camera",
                    "videoConfig": {
                        "source": "-re -i http://admin:admin@192.168.86.250/cgi/mjpg/mjpeg.cgi",
                        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 30
                    }
                }
            ]
        },
        {
          "platform": "WideQ",
          "refresh_token": "c41fc92ff7dde6cf6d5152299090724c2ce137ab6460c297166bdc6e67034c9a1dbb130de2eac77f66d1ed4f676fdb08",
          "country": "CA",
          "language": "en-CA",
          "debug": false,
          "interval": 10

        }
    ]
}
`

**Comment by NorDroN** [comment]
I fixed this problem in version 0.1.4.
And I highly recommend removing your logins, passwords, tokens from the config that you posted earlier.

**Comment by jmh600cbr** [comment]
> I fixed this problem in version 0.1.4.
> Try reinstalling this plugin - uninstall and then install it through the UI.
> And I highly recommend removing your logins, passwords, tokens from the config that you posted earlier.

so that version does fix home bridge - and it appears a new room has been added called "home" but my washing machine still isn't showing there. Any thoughts?

**Comment by NorDroN** [comment]
Please set debug = true and share your logs.

**Comment by jmh600cbr** [comment]
just spent like 3 hours trying to figure out how to find the logs on Mac OS, total messed up my configUI and don't have a backup. Will get back to you if I ever get home bridge working again.

**Comment by jmh600cbr** [comment]
> Please set debug = true, restart homebridge and share your logs.

ok just spend like 3 hours trying to figure out where the logs are on MacOS and still can't find them. 

I do have debug mode on though. I'll keep trying to find it.

**Comment by NorDroN** [comment]
This problem is still relevant?

**Comment by AmauryVela** [comment]
Yes please, I'm using the new API and I can't use your plugin :(

**Comment by chenqing212** [comment]
Hi NorDron, I am like many other posters that retrieved tokens successfully but couldn’t see the accessory in Homebridge. My LG device is a fridge and is supposed to be compatible. Thanks in advance.
